### ISSUE TITLE
Support for hash-based history

### ISSUE THREAD

**Issue by ItalyPaleAle** [kazzkiq/svero#11]
Any plans to implement support for "hash-based" history, e.g. without using the HTML5 history API?

The use case is that the app I'm working on is fully static and not a PWA. I cannot use the history API as the underlying pages don't really exist.

**Comment by kazzkiq** [comment]
That's actually an useful feature as there are always cases where you have no control over server configuration for enabling SPAs. Will dig into it.

**Comment by pateketrueke** [comment]
I was thinking about this, I'm looking to try sub-routing through hashes, but at the same time having normal routes, e.g. `/login#section` to render specific sub-views from this page.

What I want to achieve is something similar as `:target` but without CSS, because I don't want to hide/show elements this way. The reason is just avoiding too-much-DOM, and also get the netural benefits of `:target` selectors, etc.

Do you think this is also possible?

**Comment by ItalyPaleAle** [comment]
I ended up writing my own component. By focusing on hash-based routes, and dropping things like SSR, I was able to make it extremely simple.

If anyone is interested:
https://github.com/ItalyPaleAle/svelte-spa-router
