### ISSUE TITLE
New to Svelte: How would you setup this situation?

### ISSUE THREAD

**Issue by isakkeyten** [kazzkiq/svero#3]
Hey, found your router solution as I'm messing around with Svelte 3.

Let's say we need this.

Route "/" to load Main
Route "/foo" to load Foo.svelte which imports Baz.svelte
Route "/bar" to load Bar which also imports the same Baz.svelte

Now my naive approach just did it as is but this is the issue.
Baz.svelte has onMount that does a thing.
Because the router remounts the whole component, it remounts the children too.
If I take the Baz.svelte outside of the Foo and Bar and into the App.svelte outside of router, I avoid the rerenders but now it also shows on "/" which is not what I wanted.

Can you point me in the right direction?

**Comment by kazzkiq** [comment]
Svero has no view caching nor "subrouting" as of today. In this case, you have basically three options:

1. Implement a "caching" mechanism in your component, perhaps using stores, so it knows that if mounted recently, it should not be doing heavy work again, but simply load cached data.
2. Put your component (`Baz.svelte`) in `App.svelte` and decide when to show/hide it based on `onpopstate` event, so it gets independent from the views being mounted.
3. (Not wise, beware) Simply put `Baz.svelte` in both views and load it remorseless because Svelte is fast, and client-side view mounting is fast too.

Option 2 example:

```html
<!-- ./App.svelte -->
<script>
  import { Router, Route } from 'svero';

  import Main from './pages/Main.svelte';
  import Foo from './pages/Foo.svelte';
  import Bar from './pages/Bar.svelte';
  import Baz from './components/Baz.svelte';

  let currentPath = window.location.pathname;

 $: showBaz = currentPath.includes('/foo') || currentPath.includes('/bar');
</script>

<svelte:window on:popstate={() => currentPath = window.location.pathname} />

{#if showBaz}
  <Baz />
{/if}

<Router>
  <Route path="*" component={Main} />
  <Route path="/foo" component={Foo} />
  <Route path="/bar" component={Bar} />
</Router>
```

**Comment by pateketrueke** [comment]
Not sure if this is related with #19 but I suspect that moving from `new route.component` to `<svelte:component />` did help to cache up things.

I wonder if we can reproduce the original issue against the changes from the PR in order to see if rerenders are still happening.

It could be? @kazzkiq
